// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_stack(t,e,i){var s=jQuery,n=s(this),o=s("li",i),a=s("<div>").addClass("ws_effect ws_stack").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"}).appendTo(i);this.go=function(d,f,r){var l=(t.revers?1:-1)*i.width();o.each(function(t){r&&t!=f&&(this.style.zIndex=Math.max(0,this.style.zIndex-1))});var h=s(".ws_list",i),p=s("<div>").css({position:"absolute",left:0,top:0,width:"100%",height:"100%",overflow:"hidden",zIndex:4}).append(s(e.get(r?d:f)).clone()),u=s("<div>").css({position:"absolute",left:0,top:0,width:"100%",height:"100%",overflow:"hidden",zIndex:4}).append(s(e.get(r?f:d)).clone());t.responsive<3&&(p.find("img").css("width","100%"),u.find("img").css("width","100%")),r?(u.appendTo(a),p.appendTo(a)):(p.insertAfter(h),u.insertAfter(h)),r?t.fadeOut&&h.fadeOut(t.duration):(h.stop(!0,!0).hide().css({left:-d+"00%"}),t.fadeOut?h.fadeIn(t.duration):h.show());var w={left:r?l:0},c={left:r?0:.5*-l},v={left:r?0:l},g={left:(r?1:0)*i.width()*.5};t.support.transform&&(w={translate:[w.left,0,0]},c={translate:[c.left,0,0]},v={translate:[v.left,0,0]},g={translate:[g.left,0,0]}),wowAnimate(p,w,v,t.duration,t.duration*(r?0:.1),"easeInOutExpo",function(){n.trigger("effectEnd"),p.remove(),u.remove()}),wowAnimate(u,c,g,t.duration,t.duration*(r?.1:0),"easeInOutExpo")}}